CONSTANTS = {
    'SQUAD_VERSION': 2.0,

    # VOCAB CONSTANTS
    'MIN_VOCAB_OCCURRENCE': 5,

    # EMBEDDING CONSTANTS
    'EMBED_DIM': 100,

    # INPUT LENGTH CONSTRAINTS
    'MAX_CONTEXT_SENTENCE_LENGTH': 75,
    'MAX_CONTEXT_SENTENCES': 15,
    'MAX_QUESTION_SENTENCES': 1,
    'MIN_SEQUENCE_LENGTH': 3
}

